### ISSUE TITLE
Define done for Origami Fortune Teller

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/cse110-sp23-group1#13]
Once we've scoped the definition, we'll formalize it

### The user can
- provide their own fortunes
- interact intuitively with the fortune teller
- see a fortune displayed on the final flap
- reset the fortunes to default
- easily play as many times as they want

### The fortune teller
- depicts itself operating by animating appropriately
- reflects how real paper fortune tellers are played with

### The fortunes
- begin with some defaults
- are stored locally, retaining the user's changes

**Comment by adarsh249** [comment]
user can create custom fortunes and click any flap, animation occurs showing correct origami at each step, then they can click a number, animation occurs showing origami at each step, then they can click a flap to open and see their fortune - precisely whst i wrote on google form lol

**Comment by phentos** [comment]
- no failing tests

**Comment by christiansulaiman** [comment]
pretty much said the same stuff u guys mentioned + sidebar stores in localStorage correctly

**Comment by Salam-Aboul-Hosn** [comment]
Same thing as well. Make sure everything is working as intended. Animations of the svg, inputs are saved and displayed properly.

**Comment by samw0627** [comment]
Agree. Make sure users can input fortunes, animation matches how we envisioned it in the prototypes, inputs displayed properly in the right position on the origami
